name: Backend Pipeline
on: [push]
jobs:
    Unit_Testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Set up Node js
              uses: actions/setup-node@v4
              with:
                node-version: '20'
            - run: |
                cd backend
                npm i
                npm test
    Build_And_Push:
        runs-on: ubuntu-latest
        needs: Unit_Testing
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Set up Docker
              uses: docker/setup-buildx-action@v1

            - name: Build Docker Image and Push
              run: |
                cd backend
                docker --version
                docker ps


