name: Frontend Pipeline

on:
  push:

jobs:
  Unit_Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Node js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Test Cases
        run: |
          cd frontend
          npm i
          npm test

  Build_And_Push:
    runs-on: ubuntu-latest
    needs: Unit_Testing
    env:
      TAG: ${{ github.sha }}-$(uuidgen | cut -d'-' -f1)
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
      -
            name: Build and push
            uses: docker/build-push-action@v5
            with:
              context: .
              file: ./frontend/Dockerfile
              push: true
              tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest